-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity counter_module is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_stop : IN STD_LOGIC_VECTOR (0 downto 0);
    init : IN STD_LOGIC_VECTOR (0 downto 0);
    init_value : IN STD_LOGIC_VECTOR (15 downto 0);
    count_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    count_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of counter_module is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "counter_module_counter_module,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.822429,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=107,HLS_SYN_LUT=370,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv27_5F5E0FF : STD_LOGIC_VECTOR (26 downto 0) := "101111101011110000011111111";
    constant ap_const_lv20_1 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    constant ap_const_lv20_F4240 : STD_LOGIC_VECTOR (19 downto 0) := "11110100001001000000";
    constant ap_const_lv27_0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    constant ap_const_lv27_7FFFFFF : STD_LOGIC_VECTOR (26 downto 0) := "111111111111111111111111111";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal db_start_stop_inst_clean_state : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal db_start_stop_inst_counter : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal db_init_inst_clean_state : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal edge_start_stop_inst : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal db_init_inst_counter : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal internal_count : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal is_running : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal fast_count : STD_LOGIC_VECTOR (26 downto 0) := "101111101011110000100000000";
    signal init_value_read_reg_389 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal init_read_reg_395 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_db_start_stop_inst_counter_new_0_phi_fu_98_p6 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter0_db_start_stop_inst_counter_new_0_reg_95 : STD_LOGIC_VECTOR (19 downto 0);
    signal xor_ln19_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln20_fu_210_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter0_db_start_stop_reg_108 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_db_start_stop_reg_108 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_db_init_inst_counter_new_1_phi_fu_122_p6 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter1_db_init_inst_counter_new_1_reg_119 : STD_LOGIC_VECTOR (19 downto 0);
    signal xor_ln19_1_fu_239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_1_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln20_1_fu_281_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal db_init_load_fu_235_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_internal_count_loc_0_phi_fu_135_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln87_fu_353_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_internal_count_loc_0_reg_132 : STD_LOGIC_VECTOR (15 downto 0);
    signal rising_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal is_running_load_load_fu_271_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln86_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_storemerge_phi_fu_144_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_storemerge_reg_141 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln90_fu_346_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_db_init_inst_counter_new_0_phi_fu_154_p6 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter1_db_init_inst_counter_new_0_reg_151 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_mux_db_init_inst_counter_new_2_phi_fu_167_p8 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_reg_pp0_iter1_db_init_inst_counter_new_2_reg_164 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_phi_mux_internal_count_loc_2_phi_fu_184_p8 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_internal_count_loc_2_reg_181 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal xor_ln81_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal xor_ln40_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln86_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln86_1_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_init_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_162 : BOOLEAN;
    signal ap_condition_200 : BOOLEAN;
    signal ap_condition_105 : BOOLEAN;
    signal ap_condition_251 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_db_start_stop_reg_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln21_fu_217_p2 = ap_const_lv1_0) and (xor_ln19_fu_200_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_db_start_stop_reg_108 <= db_start_stop_inst_clean_state;
            elsif ((((xor_ln19_fu_200_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln21_fu_217_p2 = ap_const_lv1_1) and (xor_ln19_fu_200_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                ap_phi_reg_pp0_iter1_db_start_stop_reg_108 <= start_stop;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_db_start_stop_reg_108 <= ap_phi_reg_pp0_iter0_db_start_stop_reg_108;
            end if; 
        end if;
    end process;

    internal_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_105)) then
                if ((ap_const_boolean_1 = ap_condition_200)) then 
                    internal_count <= init_value_read_reg_389;
                elsif ((ap_const_boolean_1 = ap_condition_162)) then 
                    internal_count <= add_ln87_fu_353_p2;
                end if;
            end if; 
        end if;
    end process;

    is_running_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_105)) then
                if ((ap_const_boolean_1 = ap_condition_200)) then 
                    is_running <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_251)) then 
                    is_running <= xor_ln81_fu_312_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) then
                db_init_inst_clean_state <= init_read_reg_395;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                db_init_inst_counter <= ap_phi_mux_db_init_inst_counter_new_2_phi_fu_167_p8;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln21_fu_217_p2 = ap_const_lv1_1) and (xor_ln19_fu_200_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                db_start_stop_inst_clean_state <= start_stop;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                db_start_stop_inst_counter <= ap_phi_mux_db_start_stop_inst_counter_new_0_phi_fu_98_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1)))) then
                edge_start_stop_inst <= ap_phi_reg_pp0_iter1_db_start_stop_reg_108;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((((((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1)) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1))) or ((is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) or ((is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 
    = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0))) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0))))) then
                fast_count <= ap_phi_mux_storemerge_phi_fu_144_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                init_read_reg_395 <= init;
                init_value_read_reg_389 <= init_value;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_init_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln20_1_fu_281_p2 <= std_logic_vector(unsigned(db_init_inst_counter) + unsigned(ap_const_lv20_1));
    add_ln20_fu_210_p2 <= std_logic_vector(unsigned(db_start_stop_inst_counter) + unsigned(ap_const_lv20_1));
    add_ln87_fu_353_p2 <= std_logic_vector(unsigned(internal_count) + unsigned(ap_const_lv16_FFFF));
    add_ln90_fu_346_p2 <= std_logic_vector(unsigned(fast_count) + unsigned(ap_const_lv27_7FFFFFF));
    and_ln86_fu_340_p2 <= (icmp_ln86_fu_328_p2 and icmp_ln86_1_fu_334_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_105_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_105 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_162_assign_proc : process(init_read_reg_395, xor_ln19_1_fu_239_p2, icmp_ln21_1_fu_289_p2, db_init_load_fu_235_p1, rising_fu_254_p2, is_running_load_load_fu_271_p1, and_ln86_fu_340_p2)
    begin
                ap_condition_162 <= (((((((ap_const_lv1_1 = and_ln86_fu_340_p2) and (init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1)) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) and (init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1))) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) 
    and (init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0))) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) and (init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)));
    end process;


    ap_condition_200_assign_proc : process(init_read_reg_395, xor_ln19_1_fu_239_p2, icmp_ln21_1_fu_289_p2, db_init_load_fu_235_p1)
    begin
                ap_condition_200 <= ((((db_init_load_fu_235_p1 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1)) or ((init_read_reg_395 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1))) or ((init_read_reg_395 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)));
    end process;


    ap_condition_251_assign_proc : process(init_read_reg_395, xor_ln19_1_fu_239_p2, icmp_ln21_1_fu_289_p2, db_init_load_fu_235_p1, rising_fu_254_p2)
    begin
                ap_condition_251 <= ((((rising_fu_254_p2 = ap_const_lv1_1) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1)) or ((init_read_reg_395 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1))) or ((init_read_reg_395 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_db_init_inst_counter_new_0_phi_fu_154_p6_assign_proc : process(init_read_reg_395, xor_ln19_1_fu_239_p2, icmp_ln21_1_fu_289_p2, add_ln20_1_fu_281_p2, db_init_load_fu_235_p1, ap_phi_reg_pp0_iter1_db_init_inst_counter_new_0_reg_151)
    begin
        if (((db_init_load_fu_235_p1 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) then 
            ap_phi_mux_db_init_inst_counter_new_0_phi_fu_154_p6 <= add_ln20_1_fu_281_p2;
        elsif ((((init_read_reg_395 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)) or ((init_read_reg_395 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1)))) then 
            ap_phi_mux_db_init_inst_counter_new_0_phi_fu_154_p6 <= ap_const_lv20_0;
        else 
            ap_phi_mux_db_init_inst_counter_new_0_phi_fu_154_p6 <= ap_phi_reg_pp0_iter1_db_init_inst_counter_new_0_reg_151;
        end if; 
    end process;


    ap_phi_mux_db_init_inst_counter_new_1_phi_fu_122_p6_assign_proc : process(init_read_reg_395, ap_phi_reg_pp0_iter1_db_init_inst_counter_new_1_reg_119, xor_ln19_1_fu_239_p2, icmp_ln21_1_fu_289_p2, add_ln20_1_fu_281_p2, db_init_load_fu_235_p1)
    begin
        if (((db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) then 
            ap_phi_mux_db_init_inst_counter_new_1_phi_fu_122_p6 <= add_ln20_1_fu_281_p2;
        elsif ((((init_read_reg_395 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)) or ((init_read_reg_395 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1)))) then 
            ap_phi_mux_db_init_inst_counter_new_1_phi_fu_122_p6 <= ap_const_lv20_0;
        else 
            ap_phi_mux_db_init_inst_counter_new_1_phi_fu_122_p6 <= ap_phi_reg_pp0_iter1_db_init_inst_counter_new_1_reg_119;
        end if; 
    end process;


    ap_phi_mux_db_init_inst_counter_new_2_phi_fu_167_p8_assign_proc : process(init_read_reg_395, ap_phi_mux_db_init_inst_counter_new_1_phi_fu_122_p6, xor_ln19_1_fu_239_p2, icmp_ln21_1_fu_289_p2, db_init_load_fu_235_p1, rising_fu_254_p2, is_running_load_load_fu_271_p1, ap_phi_mux_db_init_inst_counter_new_0_phi_fu_154_p6, ap_phi_reg_pp0_iter1_db_init_inst_counter_new_2_reg_164)
    begin
        if ((((is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1)) or ((is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_1) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1)) or ((is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_0) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1)) or ((is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1)) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 
    = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1)) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1)) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1)) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 
    = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1)))) then 
            ap_phi_mux_db_init_inst_counter_new_2_phi_fu_167_p8 <= ap_phi_mux_db_init_inst_counter_new_1_phi_fu_122_p6;
        elsif (((((db_init_load_fu_235_p1 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1)) or ((init_read_reg_395 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1))) or ((init_read_reg_395 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)))) then 
            ap_phi_mux_db_init_inst_counter_new_2_phi_fu_167_p8 <= ap_phi_mux_db_init_inst_counter_new_0_phi_fu_154_p6;
        else 
            ap_phi_mux_db_init_inst_counter_new_2_phi_fu_167_p8 <= ap_phi_reg_pp0_iter1_db_init_inst_counter_new_2_reg_164;
        end if; 
    end process;


    ap_phi_mux_db_start_stop_inst_counter_new_0_phi_fu_98_p6_assign_proc : process(ap_phi_reg_pp0_iter0_db_start_stop_inst_counter_new_0_reg_95, xor_ln19_fu_200_p2, icmp_ln21_fu_217_p2, add_ln20_fu_210_p2)
    begin
        if (((icmp_ln21_fu_217_p2 = ap_const_lv1_0) and (xor_ln19_fu_200_p2 = ap_const_lv1_1))) then 
            ap_phi_mux_db_start_stop_inst_counter_new_0_phi_fu_98_p6 <= add_ln20_fu_210_p2;
        elsif (((xor_ln19_fu_200_p2 = ap_const_lv1_0) or ((icmp_ln21_fu_217_p2 = ap_const_lv1_1) and (xor_ln19_fu_200_p2 = ap_const_lv1_1)))) then 
            ap_phi_mux_db_start_stop_inst_counter_new_0_phi_fu_98_p6 <= ap_const_lv20_0;
        else 
            ap_phi_mux_db_start_stop_inst_counter_new_0_phi_fu_98_p6 <= ap_phi_reg_pp0_iter0_db_start_stop_inst_counter_new_0_reg_95;
        end if; 
    end process;


    ap_phi_mux_internal_count_loc_0_phi_fu_135_p4_assign_proc : process(internal_count, init_read_reg_395, xor_ln19_1_fu_239_p2, icmp_ln21_1_fu_289_p2, db_init_load_fu_235_p1, add_ln87_fu_353_p2, ap_phi_reg_pp0_iter1_internal_count_loc_0_reg_132, rising_fu_254_p2, is_running_load_load_fu_271_p1, and_ln86_fu_340_p2)
    begin
        if ((((((((init_read_reg_395 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1)) or ((init_read_reg_395 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1))) or ((ap_const_lv1_0 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) or ((ap_const_lv1_0 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) or ((init_read_reg_395 = ap_const_lv1_0) 
    and (ap_const_lv1_0 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0))) or ((init_read_reg_395 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)))) then 
            ap_phi_mux_internal_count_loc_0_phi_fu_135_p4 <= internal_count;
        elsif ((((((((ap_const_lv1_1 = and_ln86_fu_340_p2) and (init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1)) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) and (init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1))) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) 
    and (init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0))) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) and (init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)))) then 
            ap_phi_mux_internal_count_loc_0_phi_fu_135_p4 <= add_ln87_fu_353_p2;
        else 
            ap_phi_mux_internal_count_loc_0_phi_fu_135_p4 <= ap_phi_reg_pp0_iter1_internal_count_loc_0_reg_132;
        end if; 
    end process;


    ap_phi_mux_internal_count_loc_2_phi_fu_184_p8_assign_proc : process(internal_count, init_value_read_reg_389, init_read_reg_395, xor_ln19_1_fu_239_p2, icmp_ln21_1_fu_289_p2, db_init_load_fu_235_p1, ap_phi_mux_internal_count_loc_0_phi_fu_135_p4, rising_fu_254_p2, is_running_load_load_fu_271_p1, ap_phi_reg_pp0_iter1_internal_count_loc_2_reg_181)
    begin
        if ((((is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_1) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1)) or ((is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_0) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1)) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1)) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)) or ((init_read_reg_395 = ap_const_lv1_0) 
    and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1)))) then 
            ap_phi_mux_internal_count_loc_2_phi_fu_184_p8 <= internal_count;
        elsif ((((((((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1)) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1))) or ((is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) or ((is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) or ((init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0))) or ((init_read_reg_395 
    = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)))) then 
            ap_phi_mux_internal_count_loc_2_phi_fu_184_p8 <= ap_phi_mux_internal_count_loc_0_phi_fu_135_p4;
        elsif (((((db_init_load_fu_235_p1 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1)) or ((init_read_reg_395 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1))) or ((init_read_reg_395 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)))) then 
            ap_phi_mux_internal_count_loc_2_phi_fu_184_p8 <= init_value_read_reg_389;
        else 
            ap_phi_mux_internal_count_loc_2_phi_fu_184_p8 <= ap_phi_reg_pp0_iter1_internal_count_loc_2_reg_181;
        end if; 
    end process;


    ap_phi_mux_storemerge_phi_fu_144_p4_assign_proc : process(init_read_reg_395, xor_ln19_1_fu_239_p2, icmp_ln21_1_fu_289_p2, db_init_load_fu_235_p1, rising_fu_254_p2, is_running_load_load_fu_271_p1, and_ln86_fu_340_p2, ap_phi_reg_pp0_iter1_storemerge_reg_141, add_ln90_fu_346_p2)
    begin
        if ((((((((init_read_reg_395 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1)) or ((init_read_reg_395 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1))) or ((ap_const_lv1_0 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) or ((ap_const_lv1_0 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) or ((init_read_reg_395 = ap_const_lv1_0) 
    and (ap_const_lv1_0 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0))) or ((init_read_reg_395 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)))) then 
            ap_phi_mux_storemerge_phi_fu_144_p4 <= add_ln90_fu_346_p2;
        elsif ((((((((ap_const_lv1_1 = and_ln86_fu_340_p2) and (init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1)) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) and (init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_1))) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (db_init_load_fu_235_p1 = ap_const_lv1_0) and (icmp_ln21_1_fu_289_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_1))) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) 
    and (init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_0) and (rising_fu_254_p2 = ap_const_lv1_1) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0))) or ((ap_const_lv1_1 = and_ln86_fu_340_p2) and (init_read_reg_395 = ap_const_lv1_0) and (is_running_load_load_fu_271_p1 = ap_const_lv1_1) and (rising_fu_254_p2 = ap_const_lv1_0) and (xor_ln19_1_fu_239_p2 = ap_const_lv1_0)))) then 
            ap_phi_mux_storemerge_phi_fu_144_p4 <= ap_const_lv27_5F5E0FF;
        else 
            ap_phi_mux_storemerge_phi_fu_144_p4 <= ap_phi_reg_pp0_iter1_storemerge_reg_141;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_db_start_stop_inst_counter_new_0_reg_95 <= "XXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_db_start_stop_reg_108 <= "X";
    ap_phi_reg_pp0_iter1_db_init_inst_counter_new_0_reg_151 <= "XXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_db_init_inst_counter_new_1_reg_119 <= "XXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_db_init_inst_counter_new_2_reg_164 <= "XXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_internal_count_loc_0_reg_132 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_internal_count_loc_2_reg_181 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_storemerge_reg_141 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_init_pp0_assign_proc : process(ap_idle_pp0_0to0)
    begin
        if ((ap_idle_pp0_0to0 = ap_const_logic_1)) then 
            ap_reset_init_pp0 <= ap_const_logic_1;
        else 
            ap_reset_init_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    count_out <= ap_phi_mux_internal_count_loc_2_phi_fu_184_p8;

    count_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            count_out_ap_vld <= ap_const_logic_1;
        else 
            count_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    db_init_load_fu_235_p1 <= db_init_inst_clean_state;
    icmp_ln21_1_fu_289_p2 <= "1" when (add_ln20_1_fu_281_p2 = ap_const_lv20_F4240) else "0";
    icmp_ln21_fu_217_p2 <= "1" when (add_ln20_fu_210_p2 = ap_const_lv20_F4240) else "0";
    icmp_ln86_1_fu_334_p2 <= "0" when (internal_count = ap_const_lv16_0) else "1";
    icmp_ln86_fu_328_p2 <= "1" when (fast_count = ap_const_lv27_0) else "0";
    is_running_load_load_fu_271_p1 <= is_running;
    rising_fu_254_p2 <= (xor_ln40_fu_248_p2 and ap_phi_reg_pp0_iter1_db_start_stop_reg_108);
    xor_ln19_1_fu_239_p2 <= (init_read_reg_395 xor db_init_inst_clean_state);
    xor_ln19_fu_200_p2 <= (start_stop xor db_start_stop_inst_clean_state);
    xor_ln40_fu_248_p2 <= (edge_start_stop_inst xor ap_const_lv1_1);
    xor_ln81_fu_312_p2 <= (is_running xor ap_const_lv1_1);
end behav;
