// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="counter_module_counter_module,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.822429,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=107,HLS_SYN_LUT=370,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module counter_module (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        start_stop,
        init,
        init_value,
        count_out,
        count_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] start_stop;
input  [0:0] init;
input  [15:0] init_value;
output  [15:0] count_out;
output   count_out_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg count_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
reg   [0:0] db_start_stop_inst_clean_state;
reg   [19:0] db_start_stop_inst_counter;
reg   [0:0] db_init_inst_clean_state;
reg   [0:0] edge_start_stop_inst;
reg   [19:0] db_init_inst_counter;
reg   [15:0] internal_count;
reg   [0:0] is_running;
reg   [26:0] fast_count;
reg   [15:0] init_value_read_reg_389;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] init_read_reg_395;
reg   [19:0] ap_phi_mux_db_start_stop_inst_counter_new_0_phi_fu_98_p6;
wire   [19:0] ap_phi_reg_pp0_iter0_db_start_stop_inst_counter_new_0_reg_95;
wire   [0:0] xor_ln19_fu_200_p2;
wire   [0:0] icmp_ln21_fu_217_p2;
wire   [19:0] add_ln20_fu_210_p2;
wire   [0:0] ap_phi_reg_pp0_iter0_db_start_stop_reg_108;
reg   [0:0] ap_phi_reg_pp0_iter1_db_start_stop_reg_108;
reg   [19:0] ap_phi_mux_db_init_inst_counter_new_1_phi_fu_122_p6;
wire   [19:0] ap_phi_reg_pp0_iter1_db_init_inst_counter_new_1_reg_119;
wire   [0:0] xor_ln19_1_fu_239_p2;
wire   [0:0] icmp_ln21_1_fu_289_p2;
wire   [19:0] add_ln20_1_fu_281_p2;
wire   [0:0] db_init_load_fu_235_p1;
reg   [15:0] ap_phi_mux_internal_count_loc_0_phi_fu_135_p4;
wire   [15:0] add_ln87_fu_353_p2;
wire   [15:0] ap_phi_reg_pp0_iter1_internal_count_loc_0_reg_132;
wire   [0:0] rising_fu_254_p2;
wire   [0:0] is_running_load_load_fu_271_p1;
wire   [0:0] and_ln86_fu_340_p2;
reg   [26:0] ap_phi_mux_storemerge_phi_fu_144_p4;
wire   [26:0] ap_phi_reg_pp0_iter1_storemerge_reg_141;
wire   [26:0] add_ln90_fu_346_p2;
reg   [19:0] ap_phi_mux_db_init_inst_counter_new_0_phi_fu_154_p6;
wire   [19:0] ap_phi_reg_pp0_iter1_db_init_inst_counter_new_0_reg_151;
reg   [19:0] ap_phi_mux_db_init_inst_counter_new_2_phi_fu_167_p8;
wire   [19:0] ap_phi_reg_pp0_iter1_db_init_inst_counter_new_2_reg_164;
reg   [15:0] ap_phi_mux_internal_count_loc_2_phi_fu_184_p8;
wire   [15:0] ap_phi_reg_pp0_iter1_internal_count_loc_2_reg_181;
wire    ap_block_pp0_stage0;
wire   [0:0] xor_ln81_fu_312_p2;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] xor_ln40_fu_248_p2;
wire   [0:0] icmp_ln86_fu_328_p2;
wire   [0:0] icmp_ln86_1_fu_334_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_init_pp0;
wire    ap_enable_pp0;
reg    ap_condition_162;
reg    ap_condition_200;
reg    ap_condition_105;
reg    ap_condition_251;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 db_start_stop_inst_clean_state = 1'd0;
#0 db_start_stop_inst_counter = 20'd0;
#0 db_init_inst_clean_state = 1'd0;
#0 edge_start_stop_inst = 1'd0;
#0 db_init_inst_counter = 20'd0;
#0 internal_count = 16'd0;
#0 is_running = 1'd0;
#0 fast_count = 27'd100000000;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_217_p2 == 1'd0) & (xor_ln19_fu_200_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_db_start_stop_reg_108 <= db_start_stop_inst_clean_state;
    end else if ((((xor_ln19_fu_200_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln21_fu_217_p2 == 1'd1) & (xor_ln19_fu_200_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_reg_pp0_iter1_db_start_stop_reg_108 <= start_stop;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_db_start_stop_reg_108 <= ap_phi_reg_pp0_iter0_db_start_stop_reg_108;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_105)) begin
        if ((1'b1 == ap_condition_200)) begin
            internal_count <= init_value_read_reg_389;
        end else if ((1'b1 == ap_condition_162)) begin
            internal_count <= add_ln87_fu_353_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_105)) begin
        if ((1'b1 == ap_condition_200)) begin
            is_running <= 1'd0;
        end else if ((1'b1 == ap_condition_251)) begin
            is_running <= xor_ln81_fu_312_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln21_1_fu_289_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd1))) begin
        db_init_inst_clean_state <= init_read_reg_395;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        db_init_inst_counter <= ap_phi_mux_db_init_inst_counter_new_2_phi_fu_167_p8;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_217_p2 == 1'd1) & (xor_ln19_fu_200_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        db_start_stop_inst_clean_state <= start_stop;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        db_start_stop_inst_counter <= ap_phi_mux_db_start_stop_inst_counter_new_0_phi_fu_98_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (xor_ln19_1_fu_239_p2 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln21_1_fu_289_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd1)))) begin
        edge_start_stop_inst <= ap_phi_reg_pp0_iter1_db_start_stop_reg_108;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((((((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd1)) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1))) | ((is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) | ((is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0))) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd0))))) begin
        fast_count <= ap_phi_mux_storemerge_phi_fu_144_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        init_read_reg_395 <= init;
        init_value_read_reg_389 <= init_value;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((db_init_load_fu_235_p1 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) begin
        ap_phi_mux_db_init_inst_counter_new_0_phi_fu_154_p6 = add_ln20_1_fu_281_p2;
    end else if ((((init_read_reg_395 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0)) | ((init_read_reg_395 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd1)))) begin
        ap_phi_mux_db_init_inst_counter_new_0_phi_fu_154_p6 = 20'd0;
    end else begin
        ap_phi_mux_db_init_inst_counter_new_0_phi_fu_154_p6 = ap_phi_reg_pp0_iter1_db_init_inst_counter_new_0_reg_151;
    end
end

always @ (*) begin
    if (((db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) begin
        ap_phi_mux_db_init_inst_counter_new_1_phi_fu_122_p6 = add_ln20_1_fu_281_p2;
    end else if ((((init_read_reg_395 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd0)) | ((init_read_reg_395 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd1)))) begin
        ap_phi_mux_db_init_inst_counter_new_1_phi_fu_122_p6 = 20'd0;
    end else begin
        ap_phi_mux_db_init_inst_counter_new_1_phi_fu_122_p6 = ap_phi_reg_pp0_iter1_db_init_inst_counter_new_1_reg_119;
    end
end

always @ (*) begin
    if ((((is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1)) | ((is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd1) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1)) | ((is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd0) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1)) | ((is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1)) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd0)) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd1)) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 
    == 1'd1) & (rising_fu_254_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0)) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1)) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd0)) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd1)) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0)) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1)))) begin
        ap_phi_mux_db_init_inst_counter_new_2_phi_fu_167_p8 = ap_phi_mux_db_init_inst_counter_new_1_phi_fu_122_p6;
    end else if (((((db_init_load_fu_235_p1 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1)) | ((init_read_reg_395 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1))) | ((init_read_reg_395 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0)))) begin
        ap_phi_mux_db_init_inst_counter_new_2_phi_fu_167_p8 = ap_phi_mux_db_init_inst_counter_new_0_phi_fu_154_p6;
    end else begin
        ap_phi_mux_db_init_inst_counter_new_2_phi_fu_167_p8 = ap_phi_reg_pp0_iter1_db_init_inst_counter_new_2_reg_164;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_217_p2 == 1'd0) & (xor_ln19_fu_200_p2 == 1'd1))) begin
        ap_phi_mux_db_start_stop_inst_counter_new_0_phi_fu_98_p6 = add_ln20_fu_210_p2;
    end else if (((xor_ln19_fu_200_p2 == 1'd0) | ((icmp_ln21_fu_217_p2 == 1'd1) & (xor_ln19_fu_200_p2 == 1'd1)))) begin
        ap_phi_mux_db_start_stop_inst_counter_new_0_phi_fu_98_p6 = 20'd0;
    end else begin
        ap_phi_mux_db_start_stop_inst_counter_new_0_phi_fu_98_p6 = ap_phi_reg_pp0_iter0_db_start_stop_inst_counter_new_0_reg_95;
    end
end

always @ (*) begin
    if ((((((((init_read_reg_395 == 1'd0) & (1'd0 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd1)) | ((init_read_reg_395 == 1'd0) & (1'd0 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1))) | ((1'd0 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) | ((1'd0 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) | ((init_read_reg_395 == 1'd0) & (1'd0 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0))) | ((init_read_reg_395 == 1'd0) & (1'd0 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 
    1'd1) & (rising_fu_254_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd0)))) begin
        ap_phi_mux_internal_count_loc_0_phi_fu_135_p4 = internal_count;
    end else if ((((((((1'd1 == and_ln86_fu_340_p2) & (init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd1)) | ((1'd1 == and_ln86_fu_340_p2) & (init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1))) | ((1'd1 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) | ((1'd1 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) | ((1'd1 == and_ln86_fu_340_p2) & (init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0))) | ((1'd1 == and_ln86_fu_340_p2) & (init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 
    1'd1) & (rising_fu_254_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd0)))) begin
        ap_phi_mux_internal_count_loc_0_phi_fu_135_p4 = add_ln87_fu_353_p2;
    end else begin
        ap_phi_mux_internal_count_loc_0_phi_fu_135_p4 = ap_phi_reg_pp0_iter1_internal_count_loc_0_reg_132;
    end
end

always @ (*) begin
    if ((((is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd1) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1)) | ((is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd0) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1)) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0)) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1)) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd0)) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd1)))) begin
        ap_phi_mux_internal_count_loc_2_phi_fu_184_p8 = internal_count;
    end else if ((((((((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd1)) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1))) | ((is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) | ((is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0))) | ((init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd0)))) begin
        ap_phi_mux_internal_count_loc_2_phi_fu_184_p8 = ap_phi_mux_internal_count_loc_0_phi_fu_135_p4;
    end else if (((((db_init_load_fu_235_p1 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1)) | ((init_read_reg_395 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1))) | ((init_read_reg_395 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0)))) begin
        ap_phi_mux_internal_count_loc_2_phi_fu_184_p8 = init_value_read_reg_389;
    end else begin
        ap_phi_mux_internal_count_loc_2_phi_fu_184_p8 = ap_phi_reg_pp0_iter1_internal_count_loc_2_reg_181;
    end
end

always @ (*) begin
    if ((((((((init_read_reg_395 == 1'd0) & (1'd0 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd1)) | ((init_read_reg_395 == 1'd0) & (1'd0 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1))) | ((1'd0 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) | ((1'd0 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) | ((init_read_reg_395 == 1'd0) & (1'd0 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0))) | ((init_read_reg_395 == 1'd0) & (1'd0 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 
    1'd1) & (rising_fu_254_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd0)))) begin
        ap_phi_mux_storemerge_phi_fu_144_p4 = add_ln90_fu_346_p2;
    end else if ((((((((1'd1 == and_ln86_fu_340_p2) & (init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd1)) | ((1'd1 == and_ln86_fu_340_p2) & (init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1))) | ((1'd1 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) | ((1'd1 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) | ((1'd1 == and_ln86_fu_340_p2) & (init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0))) | ((1'd1 == and_ln86_fu_340_p2) & (init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 
    1'd1) & (rising_fu_254_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd0)))) begin
        ap_phi_mux_storemerge_phi_fu_144_p4 = 27'd99999999;
    end else begin
        ap_phi_mux_storemerge_phi_fu_144_p4 = ap_phi_reg_pp0_iter1_storemerge_reg_141;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_idle_pp0_0to0 == 1'b1)) begin
        ap_reset_init_pp0 = 1'b1;
    end else begin
        ap_reset_init_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        count_out_ap_vld = 1'b1;
    end else begin
        count_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln20_1_fu_281_p2 = (db_init_inst_counter + 20'd1);

assign add_ln20_fu_210_p2 = (db_start_stop_inst_counter + 20'd1);

assign add_ln87_fu_353_p2 = ($signed(internal_count) + $signed(16'd65535));

assign add_ln90_fu_346_p2 = ($signed(fast_count) + $signed(27'd134217727));

assign and_ln86_fu_340_p2 = (icmp_ln86_fu_328_p2 & icmp_ln86_1_fu_334_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_105 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_162 = (((((((1'd1 == and_ln86_fu_340_p2) & (init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd1)) | ((1'd1 == and_ln86_fu_340_p2) & (init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1))) | ((1'd1 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) | ((1'd1 == and_ln86_fu_340_p2) & (is_running_load_load_fu_271_p1 == 1'd1) & (rising_fu_254_p2 == 1'd0) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1))) | ((1'd1 == and_ln86_fu_340_p2) & (init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0))) | ((1'd1 == and_ln86_fu_340_p2) & (init_read_reg_395 == 1'd0) & (is_running_load_load_fu_271_p1 == 
    1'd1) & (rising_fu_254_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_200 = ((((db_init_load_fu_235_p1 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1)) | ((init_read_reg_395 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1))) | ((init_read_reg_395 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_251 = ((((rising_fu_254_p2 == 1'd1) & (db_init_load_fu_235_p1 == 1'd0) & (icmp_ln21_1_fu_289_p2 == 1'd0) & (xor_ln19_1_fu_239_p2 == 1'd1)) | ((init_read_reg_395 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (icmp_ln21_1_fu_289_p2 == 1'd1))) | ((init_read_reg_395 == 1'd0) & (rising_fu_254_p2 == 1'd1) & (xor_ln19_1_fu_239_p2 == 1'd0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_db_start_stop_inst_counter_new_0_reg_95 = 'bx;

assign ap_phi_reg_pp0_iter0_db_start_stop_reg_108 = 'bx;

assign ap_phi_reg_pp0_iter1_db_init_inst_counter_new_0_reg_151 = 'bx;

assign ap_phi_reg_pp0_iter1_db_init_inst_counter_new_1_reg_119 = 'bx;

assign ap_phi_reg_pp0_iter1_db_init_inst_counter_new_2_reg_164 = 'bx;

assign ap_phi_reg_pp0_iter1_internal_count_loc_0_reg_132 = 'bx;

assign ap_phi_reg_pp0_iter1_internal_count_loc_2_reg_181 = 'bx;

assign ap_phi_reg_pp0_iter1_storemerge_reg_141 = 'bx;

assign count_out = ap_phi_mux_internal_count_loc_2_phi_fu_184_p8;

assign db_init_load_fu_235_p1 = db_init_inst_clean_state;

assign icmp_ln21_1_fu_289_p2 = ((add_ln20_1_fu_281_p2 == 20'd1000000) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_217_p2 = ((add_ln20_fu_210_p2 == 20'd1000000) ? 1'b1 : 1'b0);

assign icmp_ln86_1_fu_334_p2 = ((internal_count != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_328_p2 = ((fast_count == 27'd0) ? 1'b1 : 1'b0);

assign is_running_load_load_fu_271_p1 = is_running;

assign rising_fu_254_p2 = (xor_ln40_fu_248_p2 & ap_phi_reg_pp0_iter1_db_start_stop_reg_108);

assign xor_ln19_1_fu_239_p2 = (init_read_reg_395 ^ db_init_inst_clean_state);

assign xor_ln19_fu_200_p2 = (start_stop ^ db_start_stop_inst_clean_state);

assign xor_ln40_fu_248_p2 = (edge_start_stop_inst ^ 1'd1);

assign xor_ln81_fu_312_p2 = (is_running ^ 1'd1);

endmodule //counter_module
